{
 "title": "Dashboard do Grafana com MySQL",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "QTD Filmes por categoria",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT SUBSTRING_INDEX(genres, ',', 1) AS category, COUNT(*) AS count\nFROM titles\nWHERE genres IS NOT NULL AND genres LIKE '%Action%'\nGROUP BY category\nORDER BY count DESC\nLIMIT 10"
    }
   ]
  },
  {
   "title": "FILMES LATINO-AMERICANOS",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    (SELECT COUNT(*) FROM titles WHERE production_countries LIKE '%AR%' AND type = 'movie') AS AR,\n    (SELECT COUNT(*) FROM titles WHERE production_countries LIKE '%BR%' AND type = 'movie') AS BR,\n    (SELECT COUNT(*) FROM titles WHERE production_countries LIKE '%CL%' AND type = 'movie') AS CL,\n    (SELECT COUNT(*) FROM titles WHERE production_countries LIKE '%CO%' AND type = 'movie') AS CO,\n    (SELECT COUNT(*) FROM titles WHERE production_countries LIKE '%EC%' AND type = 'movie') AS EC,\n    (SELECT COUNT(*) FROM titles WHERE production_countries LIKE '%MX%' AND type = 'movie') AS MX,\n    (SELECT COUNT(*) FROM titles WHERE production_countries LIKE '%PE%' AND type = 'movie') AS PE,\n    (SELECT COUNT(*) FROM titles WHERE production_countries LIKE '%UY%' AND type = 'movie') AS UY,\n    (SELECT COUNT(*) FROM titles WHERE production_countries LIKE '%VE%' AND type = 'movie') AS VE"
    }
   ]
  },
  {
   "title": "Top 10 Filmes por Pontuação IMDb",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT title, CAST(imdb_score AS UNSIGNED) AS imdb_score FROM titles WHERE imdb_score IS NOT NULL ORDER BY imdb_score DESC LIMIT 10"
    }
   ]
  },
  {
   "title": "Melhores filmes BR",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT title, CAST(imdb_score AS DECIMAL(10, 2)) AS imdb_score\nFROM titles\nWHERE imdb_score IS NOT NULL AND imdb_score != 'unassigned' AND production_countries LIKE '%BR%'\nORDER BY imdb_score DESC\nLIMIT 10"
    }
   ]
  },
  {
   "title": "Top 10 Filmes por PIOR Pontuação IMDb",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "rawSql": "SELECT title, CAST(imdb_score AS DECIMAL(10, 2)) AS imdb_score\nFROM titles\nWHERE imdb_score IS NOT NULL AND imdb_score != '0'\nORDER BY imdb_score ASC\nLIMIT 10"
    }
   ]
  },
  {
   "title": "Series com Mais temporadas",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT title, seasons\nFROM titles\nWHERE type = 'show' AND seasons IS NOT NULL\nORDER BY CAST(seasons AS UNSIGNED) DESC\nLIMIT 10\n"
    }
   ]
  },
  {
   "title": "Contagem de Títulos por Ano de Lançamento",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "rawSql": "SELECT release_year AS time, COUNT(*) AS value\nFROM titles\nWHERE release_year IS NOT NULL\nGROUP BY release_year\nORDER BY CAST(release_year AS UNSIGNED)"
    }
   ]
  },
  {
   "title": "Top 10 Pessoas por Quantidade de Créditos",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT name AS metric, COUNT(*) AS value FROM person GROUP BY name ORDER BY value DESC LIMIT 10"
    }
   ]
  }
 ]
}